In [16]:
import pickle
from scipy.cluster.vq import *
import glob

In [17]:
from PCV.clustering import hcluster
from PCV.tools import pca
from PCV.tools import imtools

In [18]:
# get list of images

imlist = glob.glob("image_sample_copy/animal_images/*.jpeg")
#imlist = imtools.get_imlist('data/image_sample/animal_images')

In [19]:
imlist

['image_sample_copy/animal_images/animal_3.jpeg',
 'image_sample_copy/animal_images/animal_2.jpeg',
 'image_sample_copy/animal_images/animal_9.jpeg',
 'image_sample_copy/animal_images/animal_10.jpeg',
 'image_sample_copy/animal_images/animal_5.jpeg',
 'image_sample_copy/animal_images/animal_4.jpeg',
 'image_sample_copy/animal_images/animal_8.jpeg',
 'image_sample_copy/animal_images/animal_7.jpeg',
 'image_sample_copy/animal_images/animal_6.jpeg',
 'image_sample_copy/animal_images/animal_1.jpeg']

In [23]:
from PIL import Image
from numpy import *
import numpy as np
from pylab import *

im = np.array(Image.open(imlist[0])) # open one image to get size
m,n = im.shape[0:2] # get the size of the images
imnbr = len(imlist) # get the number of images

In [21]:
# create matrix to store all flattened images
immatrix = numpy.array([numpy.array(Image.open(im)).flatten() for im in imlist])

In [22]:
immatrix

array([array([ 85, 135, 136, ..., 179, 169, 170], dtype=uint8),
       array([210, 222, 218, ...,  54,  22,  43], dtype=uint8),
       array([73, 64, 23, ..., 36, 27, 10], dtype=uint8),
       array([51, 53, 50, ..., 59, 54, 51], dtype=uint8),
       array([115, 103,  87, ...,  36,  65,   7], dtype=uint8),
       array([120,  81,  76, ...,  13,   8,   5], dtype=uint8),
       array([13, 21, 24, ..., 18, 22, 23], dtype=uint8),
       array([145, 147, 160, ...,  60,  43,  51], dtype=uint8),
       array([74, 83, 62, ..., 55, 38, 22], dtype=uint8),
       array([ 11,  22,   8, ..., 126, 117,  76], dtype=uint8)],
      dtype=object)

In [15]:
# perform PCA
V,S,immean = pca.pca(immatrix)

ValueError: not enough values to unpack (expected 2, got 1)