In [72]:
import pickle
from scipy.cluster.vq import *
import glob

In [73]:
from PCV.clustering import hcluster
from PCV.tools import pca
from PCV.tools import imtools

In [74]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [75]:
from sklearn.decomposition import PCA

In [76]:
# get list of images

imlist = glob.glob("image_samples/animal_images/*.jpeg")
#imlist = imtools.get_imlist('data/image_sample/animal_images')

In [77]:
imlist

['image_samples/animal_images/animal_3.jpeg',
 'image_samples/animal_images/animal_2.jpeg',
 'image_samples/animal_images/animal_9.jpeg',
 'image_samples/animal_images/animal_10.jpeg',
 'image_samples/animal_images/animal_5.jpeg',
 'image_samples/animal_images/animal_4.jpeg',
 'image_samples/animal_images/animal_8.jpeg',
 'image_samples/animal_images/animal_7.jpeg',
 'image_samples/animal_images/animal_6.jpeg',
 'image_samples/animal_images/animal_1.jpeg']

In [78]:
from PIL import Image
from numpy import *
from pylab import *

im = array(Image.open(imlist[0])) # open one image to get size
m,n = im.shape[0:2] # get the size of the images
imnbr = len(imlist) # get the number of images

In [88]:
arraylist = [array(Image.open(im)).astype(float) for im in imlist]

In [91]:
arraylist

[array([[119., 114., 105., ..., 152., 144., 139.],
        [101., 101., 103., ..., 153., 145., 142.],
        [ 87.,  82.,  80., ..., 153., 145., 146.],
        ...,
        [200., 200., 201., ..., 174., 174., 173.],
        [196., 197., 197., ..., 172., 171., 172.],
        [196., 196., 197., ..., 171., 171., 172.]]),
 array([[218., 218., 219., ..., 165., 165., 165.],
        [218., 218., 219., ..., 165., 165., 165.],
        [218., 219., 220., ..., 167., 167., 167.],
        ...,
        [171., 154., 164., ...,  28.,  37.,  33.],
        [137., 152., 158., ...,  24.,  35.,  29.],
        [158., 152., 188., ...,  20.,  31.,  33.]]),
 array([[62., 62., 63., ..., 60., 61., 62.],
        [57., 58., 58., ..., 59., 61., 62.],
        [48., 50., 52., ..., 59., 60., 61.],
        ...,
        [26., 22., 17., ..., 35., 38., 40.],
        [22., 20., 20., ..., 29., 28., 27.],
        [22., 20., 20., ..., 29., 28., 27.]]),
 array([[ 50.,  35.,  18., ..., 154., 158., 156.],
        [ 41.,  33.,  

In [92]:
shapelist = [array.data.shape for array in arraylist]

In [93]:
shapelist

[(224, 225),
 (225, 225),
 (218, 231),
 (180, 279),
 (168, 300),
 (225, 225),
 (201, 251),
 (225, 225),
 (183, 275),
 (159, 318)]

In [94]:
shapelistmean = (mean([shape[0] for shape in shapelist]),mean([shape[1] for shape in shapelist]))

In [95]:
shapelistmean

(200.8, 255.4)

In [149]:
import os
#size = 159, 225
resize = 201, 225
for infile in imlist:
    file, ext = os.path.splitext(infile)
    im = Image.open(infile).resize(resize)
    im.save(file + "_resized.jpg", "JPEG")

In [150]:
imlist_resized = glob.glob("image_samples/animal_images/*.jpg")

In [151]:
imlist_resized

['image_samples/animal_images/animal_7_resized.jpg',
 'image_samples/animal_images/animal_2_resized.jpg',
 'image_samples/animal_images/animal_1_resized.jpg',
 'image_samples/animal_images/animal_8_resized.jpg',
 'image_samples/animal_images/animal_4_resized.jpg',
 'image_samples/animal_images/animal_3_resized.jpg',
 'image_samples/animal_images/animal_10_resized.jpg',
 'image_samples/animal_images/animal_6_resized.jpg',
 'image_samples/animal_images/animal_5_resized.jpg',
 'image_samples/animal_images/animal_9_resized.jpg']

In [152]:
immatrix = array([array(Image.open(im)) for im in imlist_resized])

In [155]:
# create matrix to store all flattened images
immatrix = array([array(Image.open(im)).flatten() for im in imlist_resized])

In [156]:
shapes = [im.data.shape for im in immatrix]

In [157]:
shapes

[(45225,),
 (45225,),
 (45225,),
 (45225,),
 (45225,),
 (45225,),
 (45225,),
 (45225,),
 (45225,),
 (45225,)]

In [158]:
# perform PCA
V,S,immean = pca.pca(immatrix)

/Users/jeffreysternberg/Documents/Image_Analysis_Project/PCV/PCV/tools/pca.py:24: RuntimeWarning: invalid value encountered in sqrt
  S = sqrt(e)[::-1] # reverse since eigenvalues are in increasing order


In [185]:
pca = PCA().fit(im.data)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance');

AttributeError: 'JpegImageFile' object has no attribute 'data'

In [181]:
pca = PCA(2)  # project from 64 to 2 dimensions
projected = pca.fit_transform(im.data)
print(immatrix[0].data.shape)
print(projected.shape)

(224, 225)
(224, 2)


In [182]:
plt.scatter(projected[:, 0], projected[:, 1],
            c=im.target, edgecolor='none', alpha=0.5,
            cmap=plt.cm.get_cmap('spectral', 10))
plt.xlabel('component 1')
plt.ylabel('component 2')
plt.colorbar();

AttributeError: 'numpy.ndarray' object has no attribute 'target'