In [11]:
import imtools
import pickle
from scipy.cluster.vq import *
import glob

In [21]:
from PCV.classifiers import *
from PCV.clustering import *
from PCV.geometry import *
from PCV.imagesearch import *
from PCV.localdescriptors import *
from PCV.tools import *

In [25]:
from pcv_book.pca import *

In [51]:
from PIL import Image
from numpy import *

def pca(X):
    # get dimensions
    num_data,dim = X.shape
    
    # center data
    mean_X = X.mean(axis=0)
    X = X - mean_X
    
    if dim>num_data:
    # PCA - compact trick used
        M = dot(X,X.T) # covariance matrix
        e,EV = linalg.eigh(M) # eigenvalues and eigenvectors
        tmp = dot(X.T,EV).T # this is the compact trick
        V = tmp[::-1] # reverse since last eigenvectors are the ones we want
        S = sqrt(e)[::-1] # reverse since eigenvalues are in increasing order
        for i in range(V.shape[1]):
            V[:,i] /= S
    else:
        # PCA - SVD used
        U,S,V = linalg.svd(X)
        V = V[:num_data] # only makes sense to return the first num_data
    
    # return the projection matrix, the variance and the mean
    return V,S,mean_X

In [43]:
# get list of images

imlist = glob.glob("../data/image_sample/animal_images/*.jpeg")

In [44]:
from PIL import Image
from numpy import *
from pylab import *

im = array(Image.open(imlist[0])) # open one image to get size
m,n = im.shape[0:2] # get the size of the images
imnbr = len(imlist) # get the number of images

In [57]:
# create matrix to store all flattened images
immatrix = array([array(Image.open(im)).flatten()
for im in imlist],object)

In [70]:
immatrix

array([array([ 85, 135, 136, ..., 179, 169, 170], dtype=uint8),
       array([210, 222, 218, ...,  54,  22,  43], dtype=uint8),
       array([73, 64, 23, ..., 36, 27, 10], dtype=uint8),
       array([51, 53, 50, ..., 59, 54, 51], dtype=uint8),
       array([115, 103,  87, ...,  36,  65,   7], dtype=uint8),
       array([120,  81,  76, ...,  13,   8,   5], dtype=uint8),
       array([13, 21, 24, ..., 18, 22, 23], dtype=uint8),
       array([145, 147, 160, ...,  60,  43,  51], dtype=uint8),
       array([74, 83, 62, ..., 55, 38, 22], dtype=uint8),
       array([ 11,  22,   8, ..., 126, 117,  76], dtype=uint8)],
      dtype=object)

In [71]:
# perform PCA
V,S,immean = pca(pca(immatrix))

ValueError: not enough values to unpack (expected 2, got 1)